name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Ci-front:

    runs-on: ubuntu-latest

    env:
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
      VITE_GRAPHQL_API_URL: ${{ secrets.GRAPHQL_API_URL }}

    strategy:
      matrix:
        browser-type: [chrome, firefox, edge]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm i

    - name: Run build
      run: npm run build

    - name: Run unit test
      run: npm run test:ci

    - name: Run e2e test Cypress
      uses: cypress-io/github-action@v5.0.8
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CYPRESS_CLIENT_URL: ${{ env.CLIENT_URL }}
        CYPRESS_GRAPHQL_API_URL: ${{ env.VITE_GRAPHQL_API_URL }}
      with:
        install: false
        build: npm run build
        start: npm run start:dev
        browser: ${{ matrix.browser-type }}